name: Gerar Animação Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Gerar Animação Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: 'repereiradev'  # Substitua pelo seu nome de usuário GitHub

      - name: Enviar Animação Snake para GitHub
        uses: actions/upload-artifact@v2
        with:
          name: snake-graph
          path: ./path/to/generated/file
