name: Gerar Animação Snake

on:
  schedule:
    - cron: "0 0 * * *" # Roda diariamente
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Gerar Animação Snake
        uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}

      - name: Enviar Animação Snake para o GitHub
        run: |
          git config --global user.name "repereiradev"
          git config --global user.email "recrspereira@sapo.pt"
          git add dist/snake.svg
          git commit -m "Gerar Animação Snake"
          git push
