name: Generate Snake Animation
on:

  push:
    branches:
      - master
  schedule:
    - cron: "0 */6 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2


      - name: Gerar Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: repereiradev
          outputs: svg

      - name: Adicionar Snake ao README
        run: |
        git config --global user.name "repereiradev"
git config --global user.email "recrspereira@sapo.pt"

          git add -A
          git commit -m "Atualizar snake animation"
          git push
