name: Gerar Animação Snake

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v2

      - name: Gerar Animação Snake
        uses: Platane/snk@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_user_name: 'repereiradev'

      - name: Mover o Arquivo SVG para o Diretório Output
        run: |
          mkdir -p output
          mv dist/github-contribution-grid-snake.svg output/github-contribution-grid-snake.svg

      - name: Commit da Animação Snake
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Atualizar animação Snake'
          git push
